name: screenshots
description: Auto-generation of screenshots for Apple and Play Stores using emulators, simulators and real devices. Includes support for multiple locales and framing. Compatible with fastlane.
version: 2.1.1
homepage: https://github.com/mmcc007/screenshots
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  pub_cache: ^0.2.3
  usage: ^3.4.2

  args: ^1.6.0
  yaml: ^2.2.1
  resource: ^2.1.5
  path: ^1.8.0-nullsafety.1
  file: ^6.0.0-nullsafety.1
  xml: ^3.7.0
  archive: ^2.0.13
  platform: ^3.0.0-nullsafety.1
  process: ^4.0.0-nullsafety.1
  meta: ^1.3.0-nullsafety.3
  intl: ">=0.15.0 <1.0.0"

dev_dependencies:
  test: ^1.5.1+1
  test_api: ^0.2.5
  mockito: ^4.1.0
  pedantic: ^1.8.0+1
  quiver: '>=2.0.0 <3.0.0'
  collection: any

executables:
  screenshots: main