name: tool_base_test
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  tool_base:
    path: ../tool_base
  reporting:
    path: ../reporting

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
  mockito: ^4.1.2
