# Use the analysis options settings from the top level of the repo (not
# the ones from above, which include the `public_member_api_docs` rule).

include: ./analysis_options_global.yml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: false
  exclude:
    - "test/src/**"
    - "example/**"

linter:
  rules:
    unawaited_futures: true
    avoid_as: false # Disabled so we can gradually migrate to no implicit dynamic.
    always_put_control_body_on_new_line: false
